# Service para exponer el Analyzer API (GCP)
apiVersion: v1
kind: Service
metadata:
  name: analyzer-service
  namespace: news-analysis
  labels:
    app: news-analysis
    component: analyzer
spec:
  type: LoadBalancer  # LoadBalancer para obtener IP externa en GKE
  selector:
    app: news-analysis
    component: analyzer
  ports:
  - name: http
    protocol: TCP
    port: 80        # Puerto externo
    targetPort: 8000  # Puerto del contenedor
  sessionAffinity: ClientIP  # Mantiene la sesión con el mismo pod
