# CronJob para actualizar datos COLCAP diariamente (GCP)
apiVersion: batch/v1
kind: CronJob
metadata:
  name: colcap-updater
  namespace: news-analysis
  labels:
    app: news-analysis
    component: colcap-updater
spec:
  schedule: "0 19 * * *"  # Diariamente a las 7 PM
  timeZone: "America/Bogota"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid  # No permitir ejecuciones concurrentes
  
  jobTemplate:
    metadata:
      labels:
        app: news-analysis
        component: colcap-updater
    spec:
      activeDeadlineSeconds: 600  # Timeout de 10 minutos
      backoffLimit: 3
      
      template:
        metadata:
          labels:
            app: news-analysis
            component: colcap-updater
        spec:
          containers:
          - name: colcap-fetcher
            image: gcr.io/PROJECT_ID/news-analysis-acquirer:1.0.0
            imagePullPolicy: Always
            
            # Comando específico para COLCAP
            command: ["python", "data_acquirer/colcap_fetcher.py"]
            
            # Variables de entorno
            env:
            - name: COLCAP_DAYS
              value: "30"  # Descargar últimos 30 días
            - name: COLCAP_METHOD
              value: "auto"  # Intentar todos los métodos
            - name: PYTHONUNBUFFERED
              value: "1"
            
            # Recursos
            resources:
              requests:
                memory: "256Mi"
                cpu: "250m"
              limits:
                memory: "512Mi"
                cpu: "500m"
            
            # Volúmenes
            volumeMounts:
            - name: data-volume
              mountPath: /app/data
          
          # Política de reinicio
          restartPolicy: OnFailure
          
          # Volúmenes
          volumes:
          - name: data-volume
            persistentVolumeClaim:
              claimName: news-data-pvc
